# Test your FastAPI endpoints
@rooturl = http://127.0.0.1:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJuYW1lcyI6IkhhZSBNYXN0ZXIiLCJlbWFpbCI6ImhhZUBoYWUuY29tIiwiZXhwIjoxNzI2NzI3NTk2fQ.PBukguq5_9vP7ckjMIhsDSekiFtbG93RWrubSxdJPf4
###
POST {{rooturl}}/signup
Accept: application/json

{"first_name":"Hae", "last_name":"Master", "email":"hae@hae.com","password":"123456"}

###
POST {{rooturl}}/login
Content-Type: application/json

{"email":"hae@hae.com", "password":"123456"}

###
GET {{rooturl}}/users/me
Authorization: Bearer {{token}}

###

POST  {{rooturl}}/income/create_income
Authorization: Bearer {{token}}
Accept: application/json


{"amount":500.23, "source":"Jungle","frequency":"weekly","date_time":"2024-09-23T14:30:00"}

###
GET {{rooturl}}/income/get_income
Authorization: Bearer {{token}}
Accept: application/json


###
POST {{rooturl}}/income/get_single_income/13
Authorization: Bearer {{token}}
Accept: application/json



###
PUT {{rooturl}}/income/update_income/2
Authorization: Bearer {{token}}
Accept: application/json

{"amount": 15000.0, "source": "LAND GRABBING"}

###--------end
###-------Expenses------
###

POST {{rooturl}}/expenses/create
Authorization: Bearer {{token}}
Accept: application/json

{"amount": 312500.15, "description": "Ashabahebwa", "due_date": "2024-08-12 15:00:00", "status": "pending", "frequency": "Weekly","recurring": true}


###
GET {{rooturl}}/expenses/read/pending
Authorization: Bearer {{token}}
Accept: application/json

###
GET {{rooturl}}/expenses/read/previous_month
Authorization: Bearer {{token}}
Accept: application/json


###
PUT {{rooturl}}/expenses/update/1
Authorization: Bearer {{token}}
Accept: application/json

{"amount":8000.00, "recurring": false}


###
GET {{rooturl}}/expenses/read/recurring/true
Authorization: Bearer {{token}}
Accept: application/json


###--------end
###-------reminders------
###


POST {{rooturl}}/calendar/reminders/create
Authorization: Bearer {{token}}
Accept: application/json

{"description":"kitchen supplies","due_date":"2024-08-12 15:01:00","status":"paid","frequency":"monthly","reminder_dates":["2024-08-12 15:01:00"]}

###

GET {{rooturl}}/calendar/reminders/read/3
Authorization: Bearer {{token}}
Accept: application/json


###
PUT {{rooturl}}/calendar/reminders/update/3
Authorization: Bearer {{token}}
Accept: application/json

{"description":"man man"}



####-------reminder end
####--calendere events

POST {{rooturl}}/calendar/calendar-events/create
Authorization: Bearer {{token}}
Accept: application/json

{"title":"Jinga man Concert", "description":"Doozi Songs Perform live", "start_date": "2024-08-12 15:01:00", "end_date":"2024-09-12 15:01:00", "event_type": "income"}


###

GET {{rooturl}}/calendar/calendar-events/read
Authorization: Bearer {{token}}
Accept: application/json

###
GET {{rooturl}}/calendar/calendar-events/read/1
Authorization: Bearer {{token}}
Accept: application/json


####
PUT {{rooturl}}/calendar/calendar-events/update/1
Authorization: Bearer {{token}}
Accept: application/json

{"title":"Nwagi Concert"}
